/* eslint-disable max-lines-per-function */
import 'reflect-metadata';
import { ServiceTemplateService } from './service-template.service';

class NestedClassFixture {}

class ParentClassFixture {}

enum StringStatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE'
}

enum NumericLevelEnum {
    ZERO = 0,
    ONE = 1
}

describe('ServiceTemplateService', () => {
    const normalize = (value: string): string => value.replace(/\s+/g, ' ').trim();

    let service: ServiceTemplateService;

    beforeEach(() => {
        service = new ServiceTemplateService({ name: 'myPkg', addAllowDecorator: true } as any);
    });

    describe('enumTemplate', () => {
        it('should quote values of string enums', () => {
            const result = service.enumTemplate({
                enum: StringStatusEnum,
                enumName: 'StringStatusEnum',
                type: 'string'
            } as any);

            expect(result.enumName).toBe('StringStatusEnum');
            expect(result.keys).toEqual(["ACTIVE = 'ACTIVE'", "INACTIVE = 'INACTIVE'"]);
        });

        it('should keep numeric enum values unquoted and drop all reverse-mapping keys', () => {
            const result = service.enumTemplate({
                enum: NumericLevelEnum,
                enumName: 'NumericLevelEnum',
                type: 'number'
            } as any);

            expect(result.keys).toEqual(['ZERO = 0', 'ONE = 1']);
        });
    });

    describe('modelTemplate', () => {
        it('should extend the parent class when it has a name', () => {
            const result = service.modelTemplate('ChildDto', ['prop'], ParentClassFixture);
            expect(result).toEqual({
                name: 'ChildDto',
                properties: ['prop'],
                extendClass: 'extends ParentClassFixture'
            });
        });

        it('should not extend anything when the parent is an anonymous base', () => {
            const baseParent = Object.getPrototypeOf(class {});
            const result = service.modelTemplate('RootDto', [], baseParent);
            expect(result.extendClass).toBe('');
        });
    });

    describe('propertyTemplate', () => {
        it('should render a primitive property with the @Property decorator', () => {
            const content = normalize(service.propertyTemplate({ name: 'name', option: { type: 'string' } }, 'string'));

            expect(content).toContain('@Property({"type":"string","isAutoGenerated":true})');
            expect(content).toContain('@Allow()');
            expect(content).toContain('name: string');
            expect(content).not.toContain('@Type(');
        });

        it('should mark optional properties with a question mark and arrays with brackets', () => {
            const content = normalize(
                service.propertyTemplate(
                    { name: 'tags', option: { type: 'string', isArray: true, required: false } },
                    'string'
                )
            );

            expect(content).toContain('tags?: string []');
        });

        it('should render any-typed properties with the @AnyType decorator', () => {
            const content = normalize(
                service.propertyTemplate({ name: 'data', option: { type: 'string', format: 'any' } }, 'string')
            );

            expect(content).toContain('@AnyType()');
            expect(content).toContain('data: any');
        });

        it('should render enum properties with the enum name as type', () => {
            const content = normalize(
                service.propertyTemplate(
                    {
                        name: 'status',
                        option: { type: 'string', enum: StringStatusEnum, enumName: 'StringStatusEnum' }
                    },
                    'StringStatusEnum'
                )
            );

            expect(content).toContain('status: StringStatusEnum');
            expect(content).not.toContain('@Type(');
        });

        it('should render nested class properties with a lazy type and @Type decorator', () => {
            const content = normalize(
                service.propertyTemplate({ name: 'nested', option: { type: NestedClassFixture } }, 'NestedClassFixture')
            );

            expect(content).toContain('@Type(() => NestedClassFixture)');
            expect(content).toContain('nested: ReturnType<() => NestedClassFixture >');
            expect(content).toContain('@Property({"type": () => NestedClassFixture,"isAutoGenerated":true})');
        });

        it('should skip the @Allow decorator when it is disabled in the config', () => {
            const noAllowService = new ServiceTemplateService({ name: 'myPkg', addAllowDecorator: false } as any);
            const content = noAllowService.propertyTemplate({ name: 'name', option: { type: 'string' } }, 'string');
            expect(content).not.toContain('@Allow()');
        });
    });

    describe('templateServiceAndModel', () => {
        let content: string;

        beforeEach(() => {
            content = service.templateServiceAndModel(
                [
                    { serviceName: 'UserMicroservice', methods: ['REAL_METHOD;'], isMock: false },
                    { serviceName: 'UserMicroservice', methods: ['MOCK_METHOD;'], isMock: true }
                ],
                [{ name: 'UserDto', properties: ['USER_PROPERTY;'], extendClass: '' }],
                [{ enumName: 'StringStatusEnum', keys: ["ACTIVE = 'ACTIVE'", "INACTIVE = 'INACTIVE'"] }]
            );
        });

        it('should render the injectable service with package scoped injection tokens', () => {
            expect(content).toContain('@Injectable()');
            expect(content).toContain('export class UserMicroservice {');
            expect(content).toContain("@Inject('myPkg_PACKAGE') private client: ClientGrpc");
            expect(content).toContain("@Inject('myPkg_OPTIONS') private options: MicroserviceModuleOptionType");
            expect(content).toContain('REAL_METHOD;');
        });

        it('should render the mock service without injection', () => {
            expect(content).toContain('export class MockUserMicroservice {');
            expect(content).toContain('MOCK_METHOD;');
        });

        it('should render model classes and enum blocks', () => {
            const normalized = normalize(content);
            expect(normalized).toContain('export class UserDto { USER_PROPERTY; }');
            expect(normalized).toContain("export enum StringStatusEnum { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', }");
        });

        it('should import class-validator only when the allow decorator is enabled', () => {
            expect(content).toContain("import { Allow } from 'class-validator';");

            const noAllowService = new ServiceTemplateService({ name: 'myPkg', addAllowDecorator: false } as any);
            const noAllowContent = noAllowService.templateServiceAndModel([], [], []);
            expect(noAllowContent).not.toContain("import { Allow } from 'class-validator';");
        });
    });
});
