import { ApiPropertyOptions } from '@nestjs/swagger';
import { MockOptionType } from './mock-option.type';

export type PropertyType = { name: string; option: PropertyOptionType };

export type PropertyOptionType = {
    type?: any;
    isArray?: boolean;
    required?: boolean;
    description?: string;
    default?: any;
    mock?: MockOptionType;
    enumName?: string;
    isAutoGenerated?: boolean;
} & ApiPropertyOptions;
