/* eslint-disable max-lines-per-function */
/* eslint-disable @typescript-eslint/no-unsafe-function-type */
import 'reflect-metadata';
import { Property } from './property.decorator';
import { propertyStorage, sdkDtos } from '../storages/property.storage';
import { PropertyType } from '../types/property-option.type';

const apiModelPropertiesKey = 'swagger/apiModelProperties';

describe('Property', () => {
    let savedProperties: Array<[Function, PropertyType[]]>;
    let savedSdkDtos: Function[];

    beforeEach(() => {
        savedProperties = Array.from(propertyStorage.entries());
        savedSdkDtos = Array.from(sdkDtos);
    });

    afterEach(() => {
        propertyStorage.clear();
        for (const [key, value] of savedProperties) {
            propertyStorage.set(key, value);
        }
        sdkDtos.clear();
        for (const dto of savedSdkDtos) {
            sdkDtos.add(dto);
        }
    });

    describe('type normalization in property storage', () => {
        it('converts the String constructor to "string"', () => {
            class Dto {
                @Property({ type: String })
                name: string;
            }

            expect(propertyStorage.get(Dto)).toEqual([
                { name: 'name', option: expect.objectContaining({ type: 'string' }) }
            ]);
        });

        it('converts the Number constructor to "number"', () => {
            class Dto {
                @Property({ type: Number })
                age: number;
            }

            expect(propertyStorage.get(Dto)[0].option.type).toBe('number');
        });

        it('converts the Boolean constructor to "boolean"', () => {
            class Dto {
                @Property({ type: Boolean })
                isActive: boolean;
            }

            expect(propertyStorage.get(Dto)[0].option.type).toBe('boolean');
        });

        it('keeps string proto types as-is', () => {
            class Dto {
                @Property({ type: 'bool' as any })
                isActive: boolean;
            }

            expect(propertyStorage.get(Dto)[0].option.type).toBe('bool');
        });

        it('converts type "string" with default "any" into type "any"', () => {
            class Dto {
                @Property({ type: 'string', default: 'any' })
                data: any;
            }

            expect(propertyStorage.get(Dto)[0].option.type).toBe('any');
        });

        it('keeps class types as the class reference', () => {
            class NestedDto {
                @Property({ type: String })
                value: string;
            }

            class Dto {
                @Property({ type: NestedDto })
                nested: NestedDto;
            }

            expect(propertyStorage.get(Dto)[0].option.type).toBe(NestedDto);
        });
    });

    describe('property storage bookkeeping', () => {
        it('registers each decorated property of a class', () => {
            class Dto {
                @Property({ type: String, description: 'user name' })
                name: string;

                @Property({ type: Number, isArray: true, required: false })
                scores: number[];
            }

            const properties = propertyStorage.get(Dto);
            expect(properties).toHaveLength(2);
            expect(properties[0]).toEqual({
                name: 'name',
                option: expect.objectContaining({ type: 'string', description: 'user name' })
            });
            expect(properties[1]).toEqual({
                name: 'scores',
                option: expect.objectContaining({ type: 'number', isArray: true, required: false })
            });
        });

        it('merges options when the same property is decorated twice', () => {
            class Dto {
                name: string;
            }

            Property({ type: String })(Dto.prototype, 'name');
            Property({ type: String, description: 'merged in' })(Dto.prototype, 'name');

            const properties = propertyStorage.get(Dto);
            expect(properties).toHaveLength(1);
            expect(properties[0].option).toEqual(expect.objectContaining({ type: 'string', description: 'merged in' }));
        });

        it('adds the class to sdkDtos by default', () => {
            class Dto {
                @Property({ type: String })
                name: string;
            }

            expect(sdkDtos.has(Dto)).toBe(true);
        });

        it('does not add the class to sdkDtos when the property is auto generated', () => {
            class Dto {
                @Property({ type: String, isAutoGenerated: true })
                name: string;
            }

            expect(sdkDtos.has(Dto)).toBe(false);
            expect(propertyStorage.get(Dto)[0].option.isAutoGenerated).toBe(true);
        });
    });

    describe('swagger metadata', () => {
        it('applies ApiProperty with the proto type converted to a typescript type', () => {
            class Dto {
                @Property({ type: 'bool' as any })
                isActive: boolean;
            }

            const metadata = Reflect.getMetadata(apiModelPropertiesKey, Dto.prototype, 'isActive');
            expect(metadata.type).toBe('boolean');
        });

        it('passes class types through to ApiProperty untouched', () => {
            class NestedDto {
                @Property({ type: String })
                value: string;
            }

            class Dto {
                @Property({ type: NestedDto })
                nested: NestedDto;
            }

            const metadata = Reflect.getMetadata(apiModelPropertiesKey, Dto.prototype, 'nested');
            expect(metadata.type).toBe(NestedDto);
        });

        it('records enum metadata for enum properties with a string proto type', () => {
            enum UserTypeEnum {
                STANDARD = 'standard',
                ADMIN = 'admin'
            }

            class Dto {
                @Property({ type: 'string', enum: UserTypeEnum, enumName: 'UserTypeEnum' })
                userType: UserTypeEnum;
            }

            const metadata = Reflect.getMetadata(apiModelPropertiesKey, Dto.prototype, 'userType');
            expect(metadata.type).toBe('string');
            expect(metadata.enumName).toBe('UserTypeEnum');
            expect(metadata.enum).toEqual(['standard', 'admin']);
            expect(propertyStorage.get(Dto)[0].option.enumName).toBe('UserTypeEnum');
        });
    });
});
